version: '3.3'

services:
  web:
    build: ./verticals
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./verticals/:/usr/src/verticals/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=verticals
      - POSTGRES_PASSWORD=verticals
      - POSTGRES_DB=verticals_dev

volumes:
  postgres_data:
