version: '3.3'

services:
  web:
    build:
      context: ./verticals
      dockerfile: Dockerfile.prod
    command: gunicorn bbs_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/verticals/web/staticfiles
      - media_volume:/home/verticals/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/verticals/web/staticfiles
      - media_volume:/home/verticals/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  default:
    driver: bridge