# Test request

#cURL

# curl -i -X POST
# -H 'Accept: application/json'
# -H 'Content-Type: multipart/form-data'
# -F "title=Продам гараж"
# -F "price=1000"
# -F "author=Василий"
# -F "summary=Продам гараж. Хорошая транспортная доступность. Гараж сухой и светлый."
# -F "image=@/path/to/your_photo.jpg;type=image/jpg"
# -F "category=1"
#'http://test:QqnSnm9h6CxPSAP@127.0.0.1:8000/api/advert/create/?format=json'

# HTTP

POST http://test:QqnSnm9h6CxPSAP@127.0.0.1:8000/api/advert/create/?format=json
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

Продам гараж
--WebAppBoundary
Content-Disposition: form-data; name="price"

1000
--WebAppBoundary
Content-Disposition: form-data; name="author"

Василий
--WebAppBoundary
Content-Disposition: form-data; name="summary"

Продам гараж. Хорошая транспортная доступность. Гараж сухой и светлый.
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="your_photo.jpg"

< /path/to/your_photo.jpg
--WebAppBoundary
Content-Disposition: form-data; name="category"

1
--WebAppBoundary--

###