# Generated by Django 3.0.4 on 2020-03-21 02:10

import bbs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an advert category (e.g. Electronic, Clothes etc.)', max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter description of the ad', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=bbs.models.Advert.get_image_path)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs.Category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
