# Generated by Django 3.0.4 on 2020-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an advert category (e.g. Electronic, Clothes etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter description of the ad', max_length=1000)),
                ('category', models.ManyToManyField(help_text='Select a category for this ad', to='bbs.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
