# Generated by Django 3.0.4 on 2020-03-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20200319_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='images',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='main_image',
        ),
    ]
