# Generated by Django 3.0.4 on 2020-03-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
