# Generated by Django 3.0.4 on 2020-03-20 19:15

import bbs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bbs.models.Advert.get_image_path),
        ),
    ]
